FROM python:3.8-slim-buster

WORKDIR /app
COPY . /app
RUN pip install -r requirements.txt
EXPOSE 8080

ENV BACKUP_DIR ./backup/
ENV TABLES_FILE tables.txt
ENV MAILER_SMTPS_ADDRESS YOUR_SMTP_MAIL
ENV MAILER_SMTPS_PORT YOUR_SMTP_PORT
ENV MAILER_SENDER_MAIL YOUR_SMTP_MAIL
ENV MAILER_SENDER_PASSWORD YOUR_SMTP_PASSWORD
ENV INFLUX_HOST influxdb
ENV INFLUX_PORT 8086
ENV INFLUX_DB_NAME influx
